Repository Elonsoft/elonkit, pull requests merged in 2020-07, with the labels that each got.

#19 Add alert component
  projects/elonkit/src/ui/alert/__specs__/alert.spec.ts
  projects/elonkit/src/ui/alert/__stories__/alert-story-actions/alert-story-actions.source.ts
  projects/elonkit/src/ui/alert/__stories__/alert-story-actions/index.ts
  projects/elonkit/src/ui/alert/__stories__/alert-story-basic/alert-story-basic.source.ts
  projects/elonkit/src/ui/alert/__stories__/alert-story-basic/index.ts
  projects/elonkit/src/ui/alert/__stories__/alert-story-closable/alert-story-closable.source.ts
  projects/elonkit/src/ui/alert/__stories__/alert-story-closable/index.ts
  projects/elonkit/src/ui/alert/__stories__/alert-story-icon-mapping/alert-story-icon-mapping.component.ts
  projects/elonkit/src/ui/alert/__stories__/alert-story-icon-mapping/alert-story-icon-mapping.module.ts
  projects/elonkit/src/ui/alert/__stories__/alert-story-icon-mapping/alert-story-icon-mapping.source.ts
  projects/elonkit/src/ui/alert/__stories__/alert-story-icon-mapping/index.ts
  projects/elonkit/src/ui/alert/__stories__/alert-story-locale/alert-story-locale.component.html
  projects/elonkit/src/ui/alert/__stories__/alert-story-locale/alert-story-locale.component.ts
  projects/elonkit/src/ui/alert/__stories__/alert-story-locale/alert-story-locale.module.ts
  projects/elonkit/src/ui/alert/__stories__/alert-story-locale/alert-story-locale.source.ts
  projects/elonkit/src/ui/alert/__stories__/alert-story-locale/index.ts
  projects/elonkit/src/ui/alert/__stories__/alert.stories.mdx
  projects/elonkit/src/ui/alert/alert.component.html
  projects/elonkit/src/ui/alert/alert.component.locale.ts
  projects/elonkit/src/ui/alert/alert.component.scss
  projects/elonkit/src/ui/alert/alert.component.ts
  projects/elonkit/src/ui/alert/alert.module.ts
  projects/elonkit/src/ui/alert/alert.types.ts
  projects/elonkit/src/ui/alert/components/alert-actions/alert-actions.component.html
  projects/elonkit/src/ui/alert/components/alert-actions/alert-actions.component.scss
  projects/elonkit/src/ui/alert/components/alert-actions/alert-actions.component.ts
  projects/elonkit/src/ui/alert/components/alert-actions/index.ts
  projects/elonkit/src/ui/alert/index.ts
  projects/elonkit/src/ui/alert/ng-package.json
  projects/elonkit/src/ui/alert/public-api.ts
  projects/elonkit/storybook/assets/icons/alert/error.svg
  projects/elonkit/storybook/assets/icons/alert/warning.svg
Labels: enhancement

#22 Add empty state component
  README.md
  package.json
  projects/elonkit/src/assets/elonkit/empty-state/box.svg
  projects/elonkit/src/assets/elonkit/empty-state/chat.svg
  projects/elonkit/src/assets/elonkit/empty-state/face.svg
  projects/elonkit/src/assets/elonkit/empty-state/file.svg
  projects/elonkit/src/assets/elonkit/empty-state/search.svg
  projects/elonkit/src/ng-package.json
  projects/elonkit/src/public-api.ts
  projects/elonkit/src/ui/empty-state/__specs__/empty-state.spec.ts
  projects/elonkit/src/ui/empty-state/__stories__/empty-state-story-basic/empty-state-story-basic.source.ts
  projects/elonkit/src/ui/empty-state/__stories__/empty-state-story-basic/index.ts
  projects/elonkit/src/ui/empty-state/__stories__/empty-state-story-button/empty-state-story-button.source.ts
  projects/elonkit/src/ui/empty-state/__stories__/empty-state-story-button/index.ts
  projects/elonkit/src/ui/empty-state/__stories__/empty-state-story-typography/empty-state-story-typography.component.html
  projects/elonkit/src/ui/empty-state/__stories__/empty-state-story-typography/empty-state-story-typography.component.scss
  projects/elonkit/src/ui/empty-state/__stories__/empty-state-story-typography/empty-state-story-typography.component.ts
  projects/elonkit/src/ui/empty-state/__stories__/empty-state-story-typography/empty-state-story-typography.module.ts
  projects/elonkit/src/ui/empty-state/__stories__/empty-state-story-typography/empty-state-story-typography.source.ts
  projects/elonkit/src/ui/empty-state/__stories__/empty-state-story-typography/index.ts
  projects/elonkit/src/ui/empty-state/__stories__/empty-state.stories.mdx
  projects/elonkit/src/ui/empty-state/empty-state.component.html
  projects/elonkit/src/ui/empty-state/empty-state.component.scss
  projects/elonkit/src/ui/empty-state/empty-state.component.ts
  projects/elonkit/src/ui/empty-state/empty-state.module.ts
  projects/elonkit/src/ui/empty-state/empty-state.types.ts
  projects/elonkit/src/ui/empty-state/index.ts
  projects/elonkit/src/ui/empty-state/ng-package.json
  projects/elonkit/src/ui/empty-state/public-api.ts
  projects/elonkit/storybook/main.js
  yarn.lock
Labels: enhancement

#23 Remove counter component
  projects/elonkit/src/public-api.ts
  projects/elonkit/src/theme.scss
  projects/elonkit/src/ui/alert/alert.component.ts
  projects/elonkit/src/ui/counter/__specs__/counter.spec.ts
  projects/elonkit/src/ui/counter/__stories__/counter-story-addons/counter-story-addons.source.ts
  projects/elonkit/src/ui/counter/__stories__/counter-story-addons/index.ts
  projects/elonkit/src/ui/counter/__stories__/counter-story-basic/counter-story-basic.source.ts
  projects/elonkit/src/ui/counter/__stories__/counter-story-basic/index.ts
  projects/elonkit/src/ui/counter/__stories__/counter-story-container/counter-story-container.component.html
  projects/elonkit/src/ui/counter/__stories__/counter-story-container/counter-story-container.component.scss
  projects/elonkit/src/ui/counter/__stories__/counter-story-container/counter-story-container.component.ts
  projects/elonkit/src/ui/counter/__stories__/counter-story-container/counter-story-container.module.ts
  projects/elonkit/src/ui/counter/__stories__/counter-story-container/counter-story-container.source.ts
  projects/elonkit/src/ui/counter/__stories__/counter-story-container/index.ts
  projects/elonkit/src/ui/counter/__stories__/counter.stories.mdx
  projects/elonkit/src/ui/counter/counter.component.html
  projects/elonkit/src/ui/counter/counter.component.scss
  projects/elonkit/src/ui/counter/counter.component.theme.scss
  projects/elonkit/src/ui/counter/counter.component.ts
  projects/elonkit/src/ui/counter/counter.module.ts
  projects/elonkit/src/ui/counter/index.ts
  projects/elonkit/src/ui/counter/ng-package.json
  projects/elonkit/src/ui/counter/public-api.ts
Labels: documentation, enhancement

#12 Add action heading component
  projects/elonkit/src/public-api.ts
  projects/elonkit/src/ui/action-heading/__specs__/action-heading.spec.ts
  projects/elonkit/src/ui/action-heading/__stories__/action-heading-story-basic/action-heading-story-basic.component.html
  projects/elonkit/src/ui/action-heading/__stories__/action-heading-story-basic/action-heading-story-basic.component.scss
  projects/elonkit/src/ui/action-heading/__stories__/action-heading-story-basic/action-heading-story-basic.component.ts
  projects/elonkit/src/ui/action-heading/__stories__/action-heading-story-basic/action-heading-story-basic.module.ts
  projects/elonkit/src/ui/action-heading/__stories__/action-heading-story-basic/action-heading-story-basic.source.ts
  projects/elonkit/src/ui/action-heading/__stories__/action-heading-story-basic/index.ts
  projects/elonkit/src/ui/action-heading/__stories__/action-heading-story-click/action-heading-story-click.component.html
  projects/elonkit/src/ui/action-heading/__stories__/action-heading-story-click/action-heading-story-click.component.scss
  projects/elonkit/src/ui/action-heading/__stories__/action-heading-story-click/action-heading-story-click.component.ts
  projects/elonkit/src/ui/action-heading/__stories__/action-heading-story-click/action-heading-story-click.module.ts
  projects/elonkit/src/ui/action-heading/__stories__/action-heading-story-click/action-heading-story-click.source.ts
  projects/elonkit/src/ui/action-heading/__stories__/action-heading-story-click/index.ts
  projects/elonkit/src/ui/action-heading/__stories__/action-heading-story-customization/action-heading-story-customization.component.html
  projects/elonkit/src/ui/action-heading/__stories__/action-heading-story-customization/action-heading-story-customization.component.scss
  projects/elonkit/src/ui/action-heading/__stories__/action-heading-story-customization/action-heading-story-customization.component.ts
  projects/elonkit/src/ui/action-heading/__stories__/action-heading-story-customization/action-heading-story-customization.module.ts
  projects/elonkit/src/ui/action-heading/__stories__/action-heading-story-customization/action-heading-story-customization.source.ts
  projects/elonkit/src/ui/action-heading/__stories__/action-heading-story-customization/index.ts
  projects/elonkit/src/ui/action-heading/__stories__/action-heading.stories.mdx
  projects/elonkit/src/ui/action-heading/action-heading.component.html
  projects/elonkit/src/ui/action-heading/action-heading.component.scss
  projects/elonkit/src/ui/action-heading/action-heading.component.ts
  projects/elonkit/src/ui/action-heading/action-heading.module.ts
  projects/elonkit/src/ui/action-heading/index.ts
  projects/elonkit/src/ui/action-heading/ng-package.json
  projects/elonkit/src/ui/action-heading/public-api.ts
Labels: enhancement

#24 Add support for additional palettes
  .stylelintrc
  projects/elonkit/src/theme.scss
  projects/elonkit/src/ui/alert/alert.component.scss
  projects/elonkit/src/ui/alert/alert.component.theme.scss
  projects/elonkit/src/ui/inline-form-field/inline-form-field.component.scss
  projects/elonkit/src/ui/inline-form-field/inline-form-field.component.theme.scss
  projects/elonkit/src/ui/paginator/paginator.component.theme.scss
  projects/elonkit/storybook/preview-theme.scss
Labels: enhancement

#21 Improve documentation
  CHANGELOG.md
  CONTRIBUTING.md
  LICENSE.md
  README.md
  package.json
  projects/elonkit/src/package.json
Labels: documentation, help wanted

#27 Setup chromatic
  .github/workflows/pull_request.yml
  .gitignore
  package.json
  projects/elonkit/src/assets/elonkit/empty-state/box.svg
  projects/elonkit/src/assets/elonkit/empty-state/chat.svg
  projects/elonkit/src/assets/elonkit/empty-state/face.svg
  projects/elonkit/src/assets/elonkit/empty-state/file.svg
  projects/elonkit/src/assets/elonkit/empty-state/search.svg
  projects/elonkit/src/ui/timepicker/__stories__/timepicker-story-basic/timepicker-story-basic.component.ts
  projects/elonkit/src/ui/timepicker/__stories__/timepicker-story-required/timepicker-story-required.component.ts
  projects/elonkit/src/ui/timepicker/__stories__/timepicker-story-seconds/timepicker-story-seconds.component.ts
  yarn.lock
Labels: enhancement
