Repository Elonsoft/elonkit, pull requests merged in 2021-03, with the labels that each got.

#51 Fix production build and rework icons
  README.md
  package.json
  projects/elonkit/src/assets/elonkit/es-empty-state/bell.svg
  projects/elonkit/src/assets/elonkit/es-empty-state/box.svg
  projects/elonkit/src/assets/elonkit/es-empty-state/cart.svg
  projects/elonkit/src/assets/elonkit/es-empty-state/chat.svg
  projects/elonkit/src/assets/elonkit/es-empty-state/face.svg
  projects/elonkit/src/assets/elonkit/es-empty-state/file.svg
  projects/elonkit/src/assets/elonkit/es-empty-state/filter.svg
  projects/elonkit/src/assets/elonkit/es-empty-state/lock.svg
  projects/elonkit/src/assets/elonkit/es-empty-state/search.svg
  projects/elonkit/src/assets/elonkit/es-empty-state/smile.svg
  projects/elonkit/src/assets/elonkit/es-empty-state/wi-fi-off.svg
  projects/elonkit/src/assets/elonkit/es-empty-state/wi-fi.svg
  projects/elonkit/src/cdk/a11y/ng-package.json
  projects/elonkit/src/public-api.ts
  projects/elonkit/src/theming/__stories__/theming.stories.mdx
  projects/elonkit/src/theming/overrides.scss
  projects/elonkit/src/theming/theming.scss
  projects/elonkit/src/ui/action-heading/ng-package.json
  projects/elonkit/src/ui/alert/alert.component.ts
  projects/elonkit/src/ui/alert/ng-package.json
  projects/elonkit/src/ui/breadcrumbs/breadcrumbs.component.ts
  projects/elonkit/src/ui/breadcrumbs/ng-package.json
  projects/elonkit/src/ui/breadcrumbs/public-api.ts
  projects/elonkit/src/ui/core/core.module.ts
  projects/elonkit/src/ui/core/ng-package.json
  projects/elonkit/src/ui/core/public-api.ts
  projects/elonkit/src/ui/dropzone/dropzone.component.ts
  projects/elonkit/src/ui/dropzone/ng-package.json
  projects/elonkit/src/ui/empty-state/__stories__/empty-state.stories.mdx
  projects/elonkit/src/ui/empty-state/ng-package.json
  projects/elonkit/src/ui/icons/icons.service.ts
  projects/elonkit/src/ui/icons/icons.stories.mdx
  projects/elonkit/src/ui/icons/index.ts
  projects/elonkit/src/ui/icons/public-api.ts
  projects/elonkit/src/ui/inline-form-field/inline-form-field.component.ts
  projects/elonkit/src/ui/inline-form-field/ng-package.json
  projects/elonkit/src/ui/locale/ng-package.json
  projects/elonkit/src/ui/paginator/ng-package.json
  projects/elonkit/src/ui/timepicker/ng-package.json
  projects/elonkit/src/ui/timepicker/timepicker.component.ts
  projects/elonkit/src/ui/tooltip/ng-package.json
  projects/elonkit/src/ui/tooltip/tooltip.component.ts
  projects/elonkit/src/ui/tooltip/tooltip.directive.ts
  projects/elonkit/storybook/core.module.ts
  projects/elonkit/storybook/main.js
  projects/elonkit/storybook/preview-theme-dark.scss
  projects/elonkit/storybook/preview-theme-light.scss
  scss-bundle.config.json
  scss-bundle.overrides.config.json
  tsconfig.json
  yarn.lock
Labels: bug, enhancement

#35 Add audio player component
  projects/elonkit/src/assets/elonkit/es-audio-player/check.svg
  projects/elonkit/src/assets/elonkit/es-audio-player/chevron-left.svg
  projects/elonkit/src/assets/elonkit/es-audio-player/chevron-right.svg
  projects/elonkit/src/assets/elonkit/es-audio-player/download.svg
  projects/elonkit/src/assets/elonkit/es-audio-player/more-vert.svg
  projects/elonkit/src/assets/elonkit/es-audio-player/mute.svg
  projects/elonkit/src/assets/elonkit/es-audio-player/pause.svg
  projects/elonkit/src/assets/elonkit/es-audio-player/play.svg
  projects/elonkit/src/assets/elonkit/es-audio-player/speed.svg
  projects/elonkit/src/assets/elonkit/es-audio-player/un-mute.svg
  projects/elonkit/src/public-api.ts
  projects/elonkit/src/theming/theming.scss
  projects/elonkit/src/ui/audio-player/__specs__/audio-player.spec.ts
  projects/elonkit/src/ui/audio-player/__stories__/audio-player-story-basic/audio-player-story-basic.component.scss
  projects/elonkit/src/ui/audio-player/__stories__/audio-player-story-basic/audio-player-story-basic.component.ts
  projects/elonkit/src/ui/audio-player/__stories__/audio-player-story-basic/audio-player-story-basic.module.ts
  projects/elonkit/src/ui/audio-player/__stories__/audio-player-story-basic/audio-player-story-basic.source.ts
  projects/elonkit/src/ui/audio-player/__stories__/audio-player-story-basic/index.ts
  projects/elonkit/src/ui/audio-player/__stories__/audio-player.stories.mdx
  projects/elonkit/src/ui/audio-player/audio-player.component.html
  projects/elonkit/src/ui/audio-player/audio-player.component.scss
  projects/elonkit/src/ui/audio-player/audio-player.component.theme.scss
  projects/elonkit/src/ui/audio-player/audio-player.component.ts
  projects/elonkit/src/ui/audio-player/audio-player.module.ts
  projects/elonkit/src/ui/audio-player/components/audio-player-options/audio-player-options.component.html
  projects/elonkit/src/ui/audio-player/components/audio-player-options/audio-player-options.component.scss
  projects/elonkit/src/ui/audio-player/components/audio-player-options/audio-player-options.component.theme.scss
  projects/elonkit/src/ui/audio-player/components/audio-player-options/audio-player-options.component.ts
  projects/elonkit/src/ui/audio-player/components/audio-player-time-slider/audio-player-time-slider.component.html
  projects/elonkit/src/ui/audio-player/components/audio-player-time-slider/audio-player-time-slider.component.scss
  projects/elonkit/src/ui/audio-player/components/audio-player-time-slider/audio-player-time-slider.component.theme.scss
  projects/elonkit/src/ui/audio-player/components/audio-player-time-slider/audio-player-time-slider.component.ts
  projects/elonkit/src/ui/audio-player/components/audio-player-volume/audio-player-volume.component.html
  projects/elonkit/src/ui/audio-player/components/audio-player-volume/audio-player-volume.component.scss
  projects/elonkit/src/ui/audio-player/components/audio-player-volume/audio-player-volume.component.theme.scss
  projects/elonkit/src/ui/audio-player/components/audio-player-volume/audio-player-volume.component.ts
  projects/elonkit/src/ui/audio-player/index.ts
  projects/elonkit/src/ui/audio-player/ng-package.json
  projects/elonkit/src/ui/audio-player/public-api.ts
  projects/elonkit/src/ui/icons/icons.service.ts
  projects/elonkit/src/ui/locale/locales/en.ts
  projects/elonkit/src/ui/locale/locales/ru.ts
Labels: enhancement

#41 Add avatar component
  projects/elonkit/src/public-api.ts
  projects/elonkit/src/theming/theming.scss
  projects/elonkit/src/ui/avatar/__specs__/avatar.spec.ts
  projects/elonkit/src/ui/avatar/__stories__/avatar-story-group/avatar-story-group.source.ts
  projects/elonkit/src/ui/avatar/__stories__/avatar-story-group/index.ts
  projects/elonkit/src/ui/avatar/__stories__/avatar-story-image/avatar-story-image.source.ts
  projects/elonkit/src/ui/avatar/__stories__/avatar-story-image/index.ts
  projects/elonkit/src/ui/avatar/__stories__/avatar-story-no-image-icon/avatar-story-no-image-icon.source.ts
  projects/elonkit/src/ui/avatar/__stories__/avatar-story-no-image-icon/index.ts
  projects/elonkit/src/ui/avatar/__stories__/avatar-story-no-image-typography/avatar-story-no-image-typography.source.ts
  projects/elonkit/src/ui/avatar/__stories__/avatar-story-no-image-typography/index.ts
  projects/elonkit/src/ui/avatar/__stories__/avatar.stories.mdx
  projects/elonkit/src/ui/avatar/avatar-group.component.html
  projects/elonkit/src/ui/avatar/avatar-group.component.scss
  projects/elonkit/src/ui/avatar/avatar-group.component.theme.scss
  projects/elonkit/src/ui/avatar/avatar-group.component.ts
  projects/elonkit/src/ui/avatar/avatar.component.html
  projects/elonkit/src/ui/avatar/avatar.component.scss
  projects/elonkit/src/ui/avatar/avatar.component.theme.scss
  projects/elonkit/src/ui/avatar/avatar.component.ts
  projects/elonkit/src/ui/avatar/avatar.module.ts
  projects/elonkit/src/ui/avatar/avatar.types.ts
  projects/elonkit/src/ui/avatar/index.ts
  projects/elonkit/src/ui/avatar/public-api.ts
  projects/elonkit/src/ui/locale/locales/en.ts
  projects/elonkit/src/ui/locale/locales/ru.ts
  projects/elonkit/storybook/assets/img/es-logo.png
Labels: enhancement, unapproved

#52 Add getting started page
  projects/elonkit/src/guides/getting-started/__stories__/getting-started.stories.mdx
Labels: documentation
